machine:
  pre:
    - sudo apt-get update
    - sudo apt-get install python-dev
    - sudo python -m pip install -U pip
    - sudo pip install awsebcli --ignore-installed six
  services:
    - redis

  node:
    version: 6.9.1

